package uit.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FairyTail generated by hbm2java
 */
@Entity
@Table(name = "fairy_tail", catalog = "englishweb")
public class FairyTail implements java.io.Serializable {

	private static final long serialVersionUID = -400568635219155858L;
	private Integer idFairyTail;
	private String body;
	private String title;
	
	public FairyTail() {
	}

	public FairyTail(String body, String title) {
		this.body = body;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_fairy_tail", unique = true, nullable = false)
	public Integer getIdFairyTail() {
		return this.idFairyTail;
	}

	public void setIdFairyTail(Integer idFairyTail) {
		this.idFairyTail = idFairyTail;
	}

	@Column(name = "body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	

}
