package uit.entity;
// Generated Dec 10, 2018 9:07:14 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name = "topic", catalog = "englishweb")
public class Topic implements java.io.Serializable {

	private static final long serialVersionUID = 4479335520632662930L;
	private Integer idTopic;
	private String topicName;
	private Set<Vocabulary> vocabularies = new HashSet<Vocabulary>(0);

	public Topic() {
	}

	public Topic(String topicName) {
		this.topicName = topicName;
	}

	public Topic(String topicName, Set<Vocabulary> vocabularies) {
		this.topicName = topicName;
		this.vocabularies = vocabularies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_topic", unique = true, nullable = false)
	public Integer getIdTopic() {
		return this.idTopic;
	}

	public void setIdTopic(Integer idTopic) {
		this.idTopic = idTopic;
	}

	@Column(name = "topic_name", nullable = false, length = 100)
	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Vocabulary> getVocabularies() {
		return this.vocabularies;
	}

	public void setVocabularies(Set<Vocabulary> vocabularies) {
		this.vocabularies = vocabularies;
	}

}
